version: '3.8'

services:
  radarr-webhook:
    build: .
    container_name: radarr-webhook
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - /path/to/downloads:/mnt/downloads:ro
      - /path/to/media:/mnt/plexmedia
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DOWNLOAD_MONITOR_ENABLED=true
      - RADARR_ENABLED=true
      - SONARR_ENABLED=true
      - QBITTORRENT_ENABLED=true
      - QBITTORRENT_HOST=192.168.0.65
      - QBITTORRENT_PORT=8090
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=changeme
      - QBITTORRENT_PATH=/mnt/downloads
      - WEBHOOK_USERNAME=Make
      - WEBHOOK_PASSWORD=Parola1234

  # Optional: Include qBittorrent service if you want it in the same stack
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080" # WebUI
      - "6881:6881" # Torrent port
      - "6881:6881/udp" # Torrent port UDP
    volumes:
      - ./qbittorrent/config:/config
      - /path/to/downloads:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080 