version: '3.8'

services:
  radarr-webhook:
    build: .
    container_name: radarr-webhook
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - /path/to/downloads:/mnt/downloads:ro
      - /path/to/media:/mnt/plexmedia
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - DOWNLOAD_MONITOR_ENABLED=true
      - RADARR_ENABLED=true
      - SONARR_ENABLED=true
      - QBITTORRENT_ENABLED=true
      - QBITTORRENT_HOST=192.168.0.65
      - QBITTORRENT_PORT=8090
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=changeme
      - QBITTORRENT_PATH=/mnt/downloads
      - WEBHOOK_USERNAME=Make
      - WEBHOOK_PASSWORD=Parola1234
    # Ensure host directories exist with proper permissions
    user: "${UID:-1000}:${GID:-1000}"  # Use host user/group IDs if available