version: '3.8'

services:
  radarr-webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radarr-webhook
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - CONFIG_DIR=/app/config
      - DOWNLOAD_MONITOR_ENABLED=true
      - RADARR_ENABLED=true
      - SONARR_ENABLED=true
      - QBITTORRENT_ENABLED=true
      - QBITTORRENT_URL=http://qbittorrent:8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
      - PYTHONUNBUFFERED=1
    # Add this for debugging
    tty: true
    stdin_open: true